export const TOOL_ORDER: ToolName[] = [
  'npm',
  'pnpm',
  'yarn',
  'bun',
  'deno',
  'pip',
  'uv',
  'poetry',
  'pipenv',
  'conda',
  'rscript',
  'julia',
  'maven',
  'gradle',
  'sbt',
  'lein',
  'cargo',
  'cabal',
  'stack',
  'go',
  'flutter',
  'dotnet',
  'composer',
  'ruby',
  'bundle',
  'mix',
  'rebar3',
  'swift',
  'pod',
  'helm',
  'docker',
  'kustomize',
  'helmfile',
  'skaffold',
  'argocd',
  'flux',
  'terraform',
  'tofu',
  'ansible-galaxy',
  'gh',
  'glab',
  'pre-commit',
  'bazel',
  'pants',
  'buck2',
  'opam',
  'cpanm',
  'luarocks',
  'shards',
  'zig',
  'brew',
  'choco',
  'scoop',
  'winget',
  'asdf',
  'mise',
  'sdk',
  'apt-get',
  'dnf',
  'apk',
  'pacman',
  'nix',
  'cmake',
  'vcpkg',
  'conan'
]

export const STARTUP_REQUIRED_TOOLS: ToolName[] = ['npm', 'pip', 'maven']

export const TOOL_LABELS: Record<ToolName, string> = {
  npm: 'npm / Node.js',
  pnpm: 'pnpm',
  yarn: 'Yarn',
  bun: 'Bun',
  deno: 'Deno',
  pip: 'pip / Python',
  uv: 'uv',
  poetry: 'Poetry',
  pipenv: 'Pipenv',
  conda: 'Conda / Mamba',
  rscript: 'R / Rscript',
  julia: 'Julia',
  maven: 'Maven',
  gradle: 'Gradle',
  sbt: 'sbt / Scala',
  lein: 'Leiningen / Clojure',
  cargo: 'Cargo / Rust',
  cabal: 'Cabal / Haskell',
  stack: 'Stack / Haskell',
  go: 'Go',
  flutter: 'Flutter',
  dotnet: '.NET / dotnet',
  composer: 'Composer / PHP',
  ruby: 'Ruby',
  bundle: 'Bundler',
  mix: 'Mix / Elixir',
  rebar3: 'rebar3 / Erlang',
  swift: 'Swift',
  pod: 'CocoaPods',
  helm: 'Helm',
  docker: 'Docker',
  kustomize: 'Kustomize',
  helmfile: 'Helmfile',
  skaffold: 'Skaffold',
  argocd: 'Argo CD CLI',
  flux: 'Flux CLI',
  terraform: 'Terraform',
  tofu: 'OpenTofu',
  'ansible-galaxy': 'Ansible Galaxy',
  gh: 'GitHub CLI',
  glab: 'GitLab CLI',
  'pre-commit': 'pre-commit',
  bazel: 'Bazel',
  pants: 'Pants',
  buck2: 'Buck2',
  opam: 'opam / OCaml',
  cpanm: 'cpanminus / Perl',
  luarocks: 'LuaRocks',
  shards: 'Crystal Shards',
  zig: 'Zig',
  brew: 'Homebrew',
  choco: 'Chocolatey',
  scoop: 'Scoop',
  winget: 'Windows Package Manager',
  asdf: 'asdf',
  mise: 'mise',
  sdk: 'SDKMAN!',
  'apt-get': 'APT / apt-get',
  dnf: 'DNF',
  apk: 'Alpine apk',
  pacman: 'pacman',
  nix: 'Nix',
  cmake: 'CMake',
  vcpkg: 'vcpkg',
  conan: 'Conan'
}

export const TOOL_PLACEHOLDERS: Partial<Record<ToolName, string>> = {
  npm: 'Example: C:\\Program Files\\nodejs or npm.cmd',
  pnpm: 'Example: C:\\Program Files\\nodejs or pnpm.cmd',
  yarn: 'Example: C:\\Program Files\\nodejs or yarn.cmd',
  bun: 'Example: C:\\Users\\you\\.bun\\bin or bun.exe',
  deno: 'Example: C:\\Users\\you\\.deno\\bin or deno.exe',
  pip: 'Example: D:\\env\\python3 or python.exe',
  uv: 'Example: C:\\Users\\you\\.cargo\\bin or uv.exe',
  poetry: 'Example: C:\\Users\\you\\AppData\\Roaming\\Python\\Scripts or poetry.exe',
  pipenv: 'Example: C:\\Python\\Scripts or pipenv.exe',
  conda: 'Example: C:\\miniconda3\\Scripts or conda.exe',
  rscript: 'Example: C:\\Program Files\\R\\R-4.4.0\\bin or Rscript.exe',
  julia: 'Example: C:\\Users\\you\\AppData\\Local\\Programs\\Julia-1.11\\bin or julia.exe',
  maven: 'Example: C:\\apache-maven-3.8.8 or mvn.cmd',
  gradle: 'Example: C:\\gradle-8.7 or gradle.bat',
  sbt: 'Example: C:\\Program Files\\sbt\\bin or sbt.bat',
  lein: 'Example: C:\\leiningen\\bin or lein.bat',
  cargo: 'Example: C:\\Users\\you\\.cargo\\bin or cargo.exe',
  cabal: 'Example: C:\\Users\\you\\AppData\\Roaming\\cabal\\bin or cabal.exe',
  stack: 'Example: C:\\Users\\you\\AppData\\Roaming\\local\\bin or stack.exe',
  go: 'Example: C:\\Program Files\\Go or go.exe',
  flutter: 'Example: C:\\src\\flutter\\bin or flutter.bat',
  dotnet: 'Example: C:\\Program Files\\dotnet or dotnet.exe',
  composer: 'Example: C:\\ProgramData\\ComposerSetup\\bin or composer.bat',
  ruby: 'Example: C:\\Ruby33-x64\\bin or ruby.exe',
  bundle: 'Example: C:\\Ruby33-x64\\bin or bundle.bat',
  mix: 'Example: C:\\Program Files\\Elixir\\bin or mix.bat',
  rebar3: 'Example: C:\\rebar3 or rebar3.cmd',
  swift: 'Example: C:\\Library\\Developer\\Toolchains or swift.exe',
  pod: 'Example: /usr/local/bin or pod',
  helm: 'Example: C:\\Program Files\\Helm or helm.exe',
  docker: 'Example: C:\\Program Files\\Docker\\Docker\\resources\\bin or docker.exe',
  kustomize: 'Example: C:\\Program Files\\Kustomize or kustomize.exe',
  helmfile: 'Example: C:\\Program Files\\Helmfile or helmfile.exe',
  skaffold: 'Example: C:\\Program Files\\Skaffold or skaffold.exe',
  argocd: 'Example: C:\\Program Files\\ArgoCD or argocd.exe',
  flux: 'Example: C:\\Program Files\\Flux or flux.exe',
  terraform: 'Example: C:\\HashiCorp\\Terraform or terraform.exe',
  tofu: 'Example: C:\\OpenTofu\\bin or tofu.exe',
  'ansible-galaxy': 'Example: C:\\Python\\Scripts or ansible-galaxy.exe',
  gh: 'Example: C:\\Program Files\\GitHub CLI or gh.exe',
  glab: 'Example: C:\\Program Files\\glab or glab.exe',
  'pre-commit': 'Example: C:\\Python\\Scripts or pre-commit.exe',
  bazel: 'Example: C:\\bazel or bazel.exe',
  pants: 'Example: C:\\Users\\you\\.local\\bin or pants.exe',
  buck2: 'Example: C:\\buck2 or buck2.exe',
  opam: 'Example: C:\\opam or opam.exe',
  cpanm: 'Example: C:\\Strawberry\\perl\\site\\bin or cpanm.bat',
  luarocks: 'Example: C:\\LuaRocks or luarocks.bat',
  shards: 'Example: C:\\Crystal\\bin or shards.exe',
  zig: 'Example: C:\\zig or zig.exe',
  brew: 'Example: /opt/homebrew/bin or brew',
  choco: 'Example: C:\\ProgramData\\chocolatey\\bin or choco.exe',
  scoop: 'Example: C:\\Users\\you\\scoop\\shims or scoop.cmd',
  winget: 'Example: C:\\Users\\you\\AppData\\Local\\Microsoft\\WindowsApps or winget.exe',
  asdf: 'Example: C:\\Users\\you\\.asdf\\bin or asdf',
  mise: 'Example: C:\\Users\\you\\AppData\\Local\\mise\\bin or mise.exe',
  sdk: 'Example: C:\\Users\\you\\.sdkman\\bin or sdk',
  'apt-get': 'Example: /usr/bin or apt-get',
  dnf: 'Example: /usr/bin or dnf',
  apk: 'Example: /sbin or apk',
  pacman: 'Example: /usr/bin or pacman',
  nix: 'Example: /nix/var/nix/profiles/default/bin or nix',
  cmake: 'Example: C:\\Program Files\\CMake\\bin or cmake.exe',
  vcpkg: 'Example: C:\\vcpkg or vcpkg.exe',
  conan: 'Example: C:\\Python\\Scripts or conan.exe'
}
