import type {
  DependencyManagerDefinition,
  DependencyManagerId,
  ImplementedPackageManagerId
} from './managerRegistryTypes'

export type {
  DependencyManagerDefinition,
  DependencyManagerId,
  FuturePackageManagerId,
  ImplementedPackageManagerId,
  ManagerCapability,
  ManagerImplementationStatus,
  ManagerScope
} from './managerRegistryTypes'

export const MANAGER_DEFINITIONS: readonly DependencyManagerDefinition[] = [
  {
    id: 'npm',
    name: 'npm / Node.js',
    shortName: 'npm',
    language: 'JavaScript / TypeScript',
    ecosystem: 'Node.js',
    packageManager: 'npm',
    category: 'web',
    tools: ['npm'],
    manifestFiles: ['package.json'],
    lockFiles: ['package-lock.json', 'npm-shrinkwrap.json'],
    detectionFiles: ['package-lock.json', 'npm-shrinkwrap.json', 'package.json'],
    configFiles: ['.npmrc'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'batch-update', 'version-switch', 'dependency-tree', 'health', 'audit', 'publish', 'scripts', 'toolchain', 'registry-config', 'cache', 'lockfile'],
    scopes: ['project', 'global', 'repository', 'publish'],
    scenarios: ['front-end apps', 'Node.js services', 'Electron apps', 'developer tooling'],
    productionTools: ['npm audit', 'package lock review', 'registry and token management', 'script runner'],
    route: '/npm',
    builtIn: true,
    implemented: true,
    status: 'stable',
    searchable: true,
    healthSupported: true
  },
  {
    id: 'pip',
    name: 'pip / Python',
    shortName: 'pip',
    language: 'Python',
    ecosystem: 'Python',
    packageManager: 'pip',
    category: 'python',
    tools: ['pip'],
    manifestFiles: ['requirements.txt', 'pyproject.toml', 'setup.py'],
    lockFiles: ['requirements.lock'],
    configFiles: ['pip.conf', 'pip.ini'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'batch-update', 'version-switch', 'dependency-tree', 'health', 'audit', 'publish', 'toolchain', 'registry-config', 'cache', 'lockfile'],
    scopes: ['project', 'environment', 'global', 'repository', 'publish'],
    scenarios: ['Python services', 'AI and ML', 'automation', 'data science'],
    productionTools: ['pip check', 'pip-audit', 'pipdeptree', 'requirements export'],
    route: '/pip',
    builtIn: true,
    implemented: true,
    status: 'stable',
    searchable: true,
    healthSupported: true
  },
  {
    id: 'maven',
    name: 'Maven',
    shortName: 'Maven',
    language: 'Java / JVM',
    ecosystem: 'JVM',
    packageManager: 'Maven',
    category: 'jvm',
    tools: ['maven'],
    manifestFiles: ['pom.xml'],
    lockFiles: [],
    configFiles: ['settings.xml'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'version-switch', 'dependency-tree', 'health', 'audit', 'publish', 'tasks', 'toolchain', 'registry-config', 'cache'],
    scopes: ['project', 'global', 'repository', 'publish'],
    scenarios: ['Java services', 'Spring applications', 'enterprise backends'],
    productionTools: ['dependency:tree', 'go-offline', 'OWASP dependency-check', 'deploy repositories'],
    route: '/maven',
    builtIn: true,
    implemented: true,
    status: 'stable',
    searchable: true,
    healthSupported: true
  },
  {
    id: 'cargo',
    name: 'Cargo',
    shortName: 'Cargo',
    language: 'Rust',
    ecosystem: 'Rust',
    packageManager: 'Cargo',
    category: 'systems',
    tools: ['cargo'],
    manifestFiles: ['Cargo.toml'],
    lockFiles: ['Cargo.lock'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'version-switch', 'dependency-tree', 'health', 'audit', 'tasks', 'toolchain', 'lockfile'],
    scopes: ['project', 'environment'],
    scenarios: ['systems software', 'CLI tools', 'WebAssembly', 'services'],
    productionTools: ['cargo tree', 'cargo audit', 'feature-aware dependency changes'],
    route: '/cargo',
    builtIn: true,
    implemented: true,
    status: 'stable',
    searchable: true,
    healthSupported: true
  },
  {
    id: 'gradle',
    name: 'Gradle',
    shortName: 'Gradle',
    language: 'Java / Kotlin / Android',
    ecosystem: 'JVM',
    packageManager: 'Gradle',
    category: 'jvm',
    tools: ['gradle'],
    manifestFiles: ['build.gradle', 'build.gradle.kts', 'settings.gradle', 'settings.gradle.kts'],
    lockFiles: ['gradle.lockfile'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'version-switch', 'dependency-tree', 'health', 'tasks', 'toolchain', 'registry-config', 'lockfile'],
    scopes: ['project', 'repository'],
    scenarios: ['Android apps', 'Kotlin services', 'JVM monorepos'],
    productionTools: ['dependency insight', 'Gradle tasks', 'lockfile review'],
    route: '/gradle',
    builtIn: true,
    implemented: true,
    status: 'stable',
    searchable: true,
    healthSupported: true
  },
  {
    id: 'go',
    name: 'Go Modules',
    shortName: 'Go',
    language: 'Go',
    ecosystem: 'Go',
    packageManager: 'go modules',
    category: 'systems',
    tools: ['go'],
    manifestFiles: ['go.mod'],
    lockFiles: ['go.sum'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'version-switch', 'dependency-tree', 'health', 'audit', 'tasks', 'toolchain', 'lockfile'],
    scopes: ['project', 'environment'],
    scenarios: ['cloud services', 'CLI tools', 'microservices'],
    productionTools: ['go mod tidy', 'go mod graph', 'govulncheck'],
    route: '/go',
    builtIn: true,
    implemented: true,
    status: 'stable',
    searchable: true,
    healthSupported: true
  },
  {
    id: 'flutter',
    name: 'Flutter pub',
    shortName: 'Flutter',
    language: 'Dart / Flutter',
    ecosystem: 'Dart',
    packageManager: 'flutter pub',
    category: 'mobile',
    tools: ['flutter'],
    manifestFiles: ['pubspec.yaml'],
    lockFiles: ['pubspec.lock'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'version-switch', 'dependency-tree', 'health', 'audit', 'publish', 'tasks', 'toolchain', 'assets', 'lockfile'],
    scopes: ['project', 'repository', 'publish'],
    scenarios: ['Flutter apps', 'Dart packages', 'mobile apps', 'desktop apps', 'web apps'],
    productionTools: ['pub outdated', 'pub deps', 'pub.dev publish checks', 'OSV security audit'],
    route: '/flutter',
    builtIn: true,
    implemented: true,
    status: 'stable',
    searchable: true,
    healthSupported: true
  },
  {
    id: 'native',
    name: 'C/C++ Native',
    shortName: 'C/C++',
    language: 'C / C++',
    ecosystem: 'Native',
    packageManager: 'CMake / vcpkg / Conan',
    category: 'systems',
    tools: ['cmake', 'vcpkg', 'conan'],
    manifestFiles: ['CMakeLists.txt', 'vcpkg.json', 'conanfile.txt', 'conanfile.py'],
    lockFiles: ['vcpkg-lock.json', 'conan.lock'],
    capabilities: ['search', 'install', 'uninstall', 'dependency-tree', 'health', 'tasks', 'toolchain', 'build', 'lockfile'],
    scopes: ['project', 'environment'],
    scenarios: ['desktop native apps', 'game engines', 'embedded software', 'shared libraries'],
    productionTools: ['CMake configure/build', 'vcpkg manifests', 'Conan requirements', 'native library scan'],
    route: '/native',
    builtIn: true,
    implemented: true,
    status: 'stable',
    searchable: true,
    healthSupported: true
  },
  {
    id: 'pnpm',
    name: 'pnpm',
    shortName: 'pnpm',
    language: 'JavaScript / TypeScript',
    ecosystem: 'Node.js',
    packageManager: 'pnpm',
    category: 'web',
    tools: ['pnpm'],
    manifestFiles: ['package.json', 'pnpm-workspace.yaml'],
    lockFiles: ['pnpm-lock.yaml'],
    detectionFiles: ['pnpm-lock.yaml', 'pnpm-workspace.yaml'],
    configFiles: ['.npmrc'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'batch-update', 'dependency-tree', 'health', 'audit', 'scripts', 'toolchain', 'lockfile'],
    scopes: ['project', 'global', 'repository'],
    scenarios: ['Node.js monorepos', 'workspace-first front-end apps'],
    productionTools: ['workspace catalog review', 'lockfile diff', 'pnpm audit'],
    route: '/node',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: true,
    healthSupported: true
  },
  {
    id: 'yarn',
    name: 'Yarn',
    shortName: 'Yarn',
    language: 'JavaScript / TypeScript',
    ecosystem: 'Node.js',
    packageManager: 'Yarn',
    category: 'web',
    tools: ['yarn'],
    manifestFiles: ['package.json'],
    lockFiles: ['yarn.lock'],
    detectionFiles: ['yarn.lock'],
    configFiles: ['.yarnrc', '.yarnrc.yml'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'batch-update', 'dependency-tree', 'health', 'audit', 'scripts', 'toolchain', 'lockfile'],
    scopes: ['project', 'global', 'repository'],
    scenarios: ['front-end apps', 'monorepos', 'Plug and Play workspaces'],
    productionTools: ['Yarn constraints', 'lockfile diff', 'workspace review'],
    route: '/node',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: true,
    healthSupported: true
  },
  {
    id: 'bun',
    name: 'Bun',
    shortName: 'Bun',
    language: 'JavaScript / TypeScript',
    ecosystem: 'Bun',
    packageManager: 'bun',
    category: 'web',
    tools: ['bun'],
    manifestFiles: ['package.json'],
    lockFiles: ['bun.lock', 'bun.lockb'],
    detectionFiles: ['bun.lock', 'bun.lockb'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'dependency-tree', 'health', 'audit', 'scripts', 'toolchain', 'lockfile'],
    scopes: ['project', 'global'],
    scenarios: ['Bun applications', 'fast JavaScript tooling'],
    productionTools: ['lockfile review', 'script runner'],
    route: '/node',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: true,
    healthSupported: true
  },
  {
    id: 'deno',
    name: 'Deno',
    shortName: 'Deno',
    language: 'JavaScript / TypeScript',
    ecosystem: 'Deno',
    packageManager: 'deno',
    category: 'web',
    tools: ['deno'],
    manifestFiles: ['deno.json', 'deno.jsonc'],
    lockFiles: ['deno.lock'],
    capabilities: ['install', 'update', 'dependency-tree', 'audit', 'tasks', 'toolchain', 'lockfile'],
    scopes: ['project', 'environment'],
    scenarios: ['Deno services', 'edge functions', 'secure scripts'],
    productionTools: ['import map review', 'lockfile diff', 'permission audit'],
    route: '/platform',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: false,
    healthSupported: true
  },
  {
    id: 'uv',
    name: 'uv',
    shortName: 'uv',
    language: 'Python',
    ecosystem: 'Python',
    packageManager: 'uv',
    category: 'python',
    tools: ['uv'],
    manifestFiles: ['pyproject.toml'],
    lockFiles: ['uv.lock'],
    detectionFiles: ['uv.lock'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'batch-update', 'version-switch', 'dependency-tree', 'health', 'audit', 'toolchain', 'lockfile'],
    scopes: ['project', 'environment'],
    scenarios: ['fast Python environments', 'workspace Python projects'],
    productionTools: ['lockfile diff', 'environment sync', 'Python version pinning'],
    route: '/python',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: true,
    healthSupported: true
  },
  {
    id: 'poetry',
    name: 'Poetry',
    shortName: 'Poetry',
    language: 'Python',
    ecosystem: 'Python',
    packageManager: 'Poetry',
    category: 'python',
    tools: ['poetry'],
    manifestFiles: ['pyproject.toml'],
    lockFiles: ['poetry.lock'],
    detectionFiles: ['poetry.lock'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'batch-update', 'dependency-tree', 'health', 'audit', 'publish', 'toolchain', 'lockfile'],
    scopes: ['project', 'environment', 'publish'],
    scenarios: ['Python libraries', 'Python services'],
    productionTools: ['lockfile diff', 'publish checks', 'virtualenv management'],
    route: '/python',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: true,
    healthSupported: true
  },
  {
    id: 'pipenv',
    name: 'Pipenv',
    shortName: 'Pipenv',
    language: 'Python',
    ecosystem: 'Python',
    packageManager: 'Pipenv',
    category: 'python',
    tools: ['pipenv'],
    manifestFiles: ['Pipfile'],
    lockFiles: ['Pipfile.lock'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'dependency-tree', 'health', 'audit', 'toolchain', 'lockfile'],
    scopes: ['project', 'environment'],
    scenarios: ['legacy Python applications', 'virtualenv-based projects'],
    productionTools: ['lockfile diff', 'pipenv check'],
    route: '/python',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: true,
    healthSupported: true
  },
  {
    id: 'conda',
    name: 'Conda / Mamba',
    shortName: 'Conda',
    language: 'Python / Data Science',
    ecosystem: 'Conda',
    packageManager: 'conda',
    category: 'python',
    tools: ['conda'],
    manifestFiles: ['environment.yml', 'environment.yaml'],
    lockFiles: ['conda-lock.yml', 'conda-lock.yaml'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'health', 'toolchain', 'lockfile'],
    scopes: ['environment', 'global'],
    scenarios: ['data science', 'AI and ML', 'reproducible environments'],
    productionTools: ['environment export', 'environment diff', 'channel policy'],
    route: '/python',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: true,
    healthSupported: true
  },
  {
    id: 'renv',
    name: 'R / renv',
    shortName: 'renv',
    language: 'R',
    ecosystem: 'R',
    packageManager: 'renv',
    category: 'data',
    tools: ['rscript'],
    manifestFiles: ['DESCRIPTION', 'renv.lock'],
    lockFiles: ['renv.lock'],
    configFiles: ['.Rprofile', 'renv/settings.json'],
    detectionFiles: ['renv.lock', 'DESCRIPTION'],
    capabilities: ['install', 'uninstall', 'update', 'dependency-tree', 'audit', 'tasks', 'toolchain', 'lockfile'],
    scopes: ['project', 'environment', 'repository'],
    scenarios: ['R packages', 'data science notebooks', 'statistical pipelines', 'reproducible research'],
    productionTools: ['renv restore', 'renv snapshot', 'package lock review'],
    route: '/data',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  },
  {
    id: 'julia',
    name: 'Julia Pkg',
    shortName: 'Julia',
    language: 'Julia',
    ecosystem: 'Julia',
    packageManager: 'Pkg',
    category: 'data',
    tools: ['julia'],
    manifestFiles: ['Project.toml'],
    lockFiles: ['Manifest.toml'],
    capabilities: ['install', 'uninstall', 'update', 'dependency-tree', 'audit', 'tasks', 'toolchain', 'lockfile'],
    scopes: ['project', 'environment', 'repository'],
    scenarios: ['scientific computing', 'data science', 'numerical services', 'research packages'],
    productionTools: ['Pkg.instantiate', 'Pkg.status', 'Manifest.toml review'],
    route: '/data',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  },
  {
    id: 'nuget',
    name: 'NuGet / dotnet',
    shortName: 'NuGet',
    language: '.NET / C#',
    ecosystem: '.NET',
    packageManager: 'NuGet',
    category: 'dotnet',
    tools: ['dotnet'],
    manifestFiles: ['*.csproj', '*.fsproj', 'Directory.Packages.props', 'packages.config'],
    lockFiles: ['packages.lock.json'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'dependency-tree', 'health', 'audit', 'publish', 'toolchain', 'lockfile'],
    scopes: ['project', 'repository', 'publish'],
    scenarios: ['ASP.NET services', 'desktop apps', 'libraries'],
    productionTools: ['dotnet list package', 'vulnerability audit', 'central package management'],
    route: '/backend',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: true,
    healthSupported: true
  },
  {
    id: 'composer',
    name: 'Composer',
    shortName: 'Composer',
    language: 'PHP',
    ecosystem: 'PHP',
    packageManager: 'Composer',
    category: 'php',
    tools: ['composer'],
    manifestFiles: ['composer.json'],
    lockFiles: ['composer.lock'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'dependency-tree', 'health', 'audit', 'publish', 'toolchain', 'lockfile'],
    scopes: ['project', 'global', 'repository', 'publish'],
    scenarios: ['PHP services', 'Laravel apps', 'WordPress tooling'],
    productionTools: ['composer audit', 'lockfile diff', 'platform requirement check'],
    route: '/backend',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: true,
    healthSupported: true
  },
  {
    id: 'bundler',
    name: 'RubyGems / Bundler',
    shortName: 'Bundler',
    language: 'Ruby',
    ecosystem: 'Ruby',
    packageManager: 'Bundler',
    category: 'ruby',
    tools: ['ruby', 'bundle'],
    manifestFiles: ['Gemfile', '*.gemspec'],
    lockFiles: ['Gemfile.lock'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'dependency-tree', 'health', 'audit', 'publish', 'toolchain', 'lockfile'],
    scopes: ['project', 'global', 'publish'],
    scenarios: ['Rails apps', 'Ruby libraries', 'automation scripts'],
    productionTools: ['bundle audit', 'lockfile diff', 'Ruby version pinning'],
    route: '/backend',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: true,
    healthSupported: true
  },
  {
    id: 'sbt',
    name: 'sbt',
    shortName: 'sbt',
    language: 'Scala / JVM',
    ecosystem: 'JVM',
    packageManager: 'sbt',
    category: 'jvm',
    tools: ['sbt'],
    manifestFiles: ['build.sbt', 'project/plugins.sbt'],
    lockFiles: ['dependency-lock.sbt'],
    configFiles: ['project/build.properties'],
    capabilities: ['install', 'update', 'dependency-tree', 'audit', 'tasks', 'toolchain', 'lockfile'],
    scopes: ['project', 'repository'],
    scenarios: ['Scala services', 'Spark jobs', 'JVM libraries'],
    productionTools: ['sbt update', 'dependencyTree', 'evicted dependency review'],
    route: '/polyglot',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  },
  {
    id: 'leiningen',
    name: 'Leiningen',
    shortName: 'Lein',
    language: 'Clojure / JVM',
    ecosystem: 'JVM',
    packageManager: 'Leiningen',
    category: 'jvm',
    tools: ['lein'],
    manifestFiles: ['project.clj'],
    lockFiles: [],
    capabilities: ['install', 'update', 'dependency-tree', 'audit', 'tasks', 'toolchain'],
    scopes: ['project', 'repository'],
    scenarios: ['Clojure services', 'JVM applications', 'data processing'],
    productionTools: ['lein deps', 'dependency tree', 'nvd-clojure audit'],
    route: '/polyglot',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  },
  {
    id: 'mix',
    name: 'Mix',
    shortName: 'Mix',
    language: 'Elixir',
    ecosystem: 'BEAM',
    packageManager: 'Mix / Hex',
    category: 'beam',
    tools: ['mix'],
    manifestFiles: ['mix.exs'],
    lockFiles: ['mix.lock'],
    configFiles: ['config/config.exs'],
    capabilities: ['install', 'uninstall', 'update', 'dependency-tree', 'audit', 'tasks', 'toolchain', 'lockfile'],
    scopes: ['project', 'repository', 'publish'],
    scenarios: ['Phoenix apps', 'Elixir services', 'Hex packages'],
    productionTools: ['mix deps.audit', 'mix hex.audit', 'mix deps.tree'],
    route: '/polyglot',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  },
  {
    id: 'rebar3',
    name: 'rebar3',
    shortName: 'rebar3',
    language: 'Erlang',
    ecosystem: 'BEAM',
    packageManager: 'rebar3',
    category: 'beam',
    tools: ['rebar3'],
    manifestFiles: ['rebar.config'],
    lockFiles: ['rebar.lock'],
    capabilities: ['install', 'update', 'dependency-tree', 'audit', 'tasks', 'toolchain', 'lockfile'],
    scopes: ['project', 'repository'],
    scenarios: ['Erlang services', 'OTP applications', 'BEAM libraries'],
    productionTools: ['rebar3 tree', 'lockfile review', 'Hex dependency audit'],
    route: '/polyglot',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  },
  {
    id: 'cabal',
    name: 'Cabal',
    shortName: 'Cabal',
    language: 'Haskell',
    ecosystem: 'Haskell',
    packageManager: 'Cabal',
    category: 'functional',
    tools: ['cabal'],
    manifestFiles: ['*.cabal', 'cabal.project'],
    lockFiles: ['cabal.project.freeze'],
    capabilities: ['install', 'update', 'dependency-tree', 'audit', 'tasks', 'toolchain', 'lockfile'],
    scopes: ['project', 'repository'],
    scenarios: ['Haskell services', 'libraries', 'CLI tools'],
    productionTools: ['cabal freeze', 'cabal outdated', 'plan review'],
    route: '/polyglot',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  },
  {
    id: 'stack',
    name: 'Stack',
    shortName: 'Stack',
    language: 'Haskell',
    ecosystem: 'Haskell',
    packageManager: 'Stack',
    category: 'functional',
    tools: ['stack'],
    manifestFiles: ['stack.yaml', 'package.yaml', '*.cabal'],
    lockFiles: ['stack.yaml.lock'],
    capabilities: ['install', 'update', 'dependency-tree', 'audit', 'tasks', 'toolchain', 'lockfile'],
    scopes: ['project', 'repository'],
    scenarios: ['Haskell applications', 'snapshot-pinned builds'],
    productionTools: ['stack ls dependencies', 'resolver pinning', 'lockfile review'],
    route: '/polyglot',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  },
  {
    id: 'swiftpm',
    name: 'Swift Package Manager',
    shortName: 'SwiftPM',
    language: 'Swift',
    ecosystem: 'Apple',
    packageManager: 'SwiftPM',
    category: 'platform',
    tools: ['swift'],
    manifestFiles: ['Package.swift'],
    lockFiles: ['Package.resolved'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'toolchain', 'lockfile'],
    scopes: ['project', 'repository'],
    scenarios: ['iOS apps', 'macOS apps', 'legacy Apple dependency stacks'],
    productionTools: ['Package.resolved diff', 'repo update policy'],
    route: '/platform',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: false,
    healthSupported: true

  },
  {
    id: 'cocoapods',
    name: 'CocoaPods',
    shortName: 'Pods',
    language: 'Objective-C / Swift',
    ecosystem: 'Apple',
    packageManager: 'CocoaPods',
    category: 'apple',
    tools: ['pod'],
    manifestFiles: ['Podfile'],
    lockFiles: ['Podfile.lock'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'toolchain', 'lockfile'],
    scopes: ['project'],
    scenarios: ['iOS apps', 'macOS apps', 'legacy Apple dependency stacks'],
    productionTools: ['Podfile.lock diff', 'repo update policy'],
    route: '/platform',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: false,
    healthSupported: true
  },
  {
    id: 'helm',
    name: 'Helm',
    shortName: 'Helm',
    language: 'Kubernetes',
    ecosystem: 'Cloud Native',
    packageManager: 'Helm',
    category: 'cloud',
    tools: ['helm'],
    manifestFiles: ['Chart.yaml'],
    lockFiles: ['Chart.lock'],
    capabilities: ['search', 'install', 'update', 'audit', 'publish', 'toolchain', 'lockfile'],
    scopes: ['project', 'repository', 'publish'],
    scenarios: ['Kubernetes charts', 'platform engineering'],
    productionTools: ['chart dependency update', 'values review', 'repository policy'],
    route: '/cloud',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: false,
    healthSupported: true

  },
  {
    id: 'docker',
    name: 'Docker Images',
    shortName: 'Docker',
    language: 'Containers',
    ecosystem: 'Containers',
    packageManager: 'Docker',
    category: 'cloud',
    tools: ['docker'],
    manifestFiles: ['Dockerfile', 'docker-compose.yml', 'compose.yaml'],
    lockFiles: [],
    capabilities: ['audit', 'toolchain', 'container-scan', 'sbom', 'license-policy'],
    scopes: ['project', 'environment'],
    scenarios: ['containerized services', 'base image governance', 'supply-chain review'],
    productionTools: ['base image scan', 'SBOM export', 'image policy'],
    route: '/cloud',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: false,
    healthSupported: true
  },
  {
    id: 'kustomize',
    name: 'Kustomize',
    shortName: 'Kustomize',
    language: 'Kubernetes YAML',
    ecosystem: 'Cloud Native',
    packageManager: 'kustomize',
    category: 'cloud',
    tools: ['kustomize'],
    manifestFiles: ['kustomization.yaml', 'kustomization.yml', 'Kustomization'],
    lockFiles: [],
    capabilities: ['update', 'dependency-tree', 'audit', 'tasks', 'toolchain', 'container-scan'],
    scopes: ['project', 'repository'],
    scenarios: ['Kubernetes overlays', 'environment promotion', 'base/component reuse', 'image tag governance'],
    productionTools: ['kustomize build', 'image tag review', 'remote base pin review'],
    route: '/cloud',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: false,
    healthSupported: true
  },
  {
    id: 'helmfile',
    name: 'Helmfile',
    shortName: 'Helmfile',
    language: 'Kubernetes YAML',
    ecosystem: 'Cloud Native',
    packageManager: 'helmfile',
    category: 'cloud',
    tools: ['helmfile'],
    manifestFiles: ['helmfile.yaml', 'helmfile.yml'],
    lockFiles: ['helmfile.lock'],
    capabilities: ['install', 'update', 'dependency-tree', 'audit', 'tasks', 'toolchain', 'lockfile'],
    scopes: ['project', 'repository'],
    scenarios: ['multi-chart releases', 'cluster environment bundles', 'Helm release promotion', 'GitOps chart baselines'],
    productionTools: ['helmfile deps', 'helmfile diff', 'helmfile lint', 'helmfile template'],
    route: '/cloud',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: false,
    healthSupported: true
  },
  {
    id: 'skaffold',
    name: 'Skaffold',
    shortName: 'Skaffold',
    language: 'Kubernetes delivery',
    ecosystem: 'Cloud Native',
    packageManager: 'skaffold',
    category: 'cloud',
    tools: ['skaffold'],
    manifestFiles: ['skaffold.yaml', 'skaffold.yml'],
    lockFiles: [],
    capabilities: ['build', 'tasks', 'audit', 'toolchain', 'container-scan'],
    scopes: ['project', 'repository'],
    scenarios: ['Kubernetes developer loops', 'image build/deploy pipelines', 'profile-based delivery', 'release render evidence'],
    productionTools: ['skaffold render', 'skaffold diagnose', 'artifact image review'],
    route: '/cloud',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: false,
    healthSupported: true
  },
  {
    id: 'argocd',
    name: 'Argo CD Applications',
    shortName: 'Argo CD',
    language: 'GitOps manifests',
    ecosystem: 'Cloud Native',
    packageManager: 'argocd',
    category: 'cloud',
    tools: ['argocd'],
    manifestFiles: ['argocd-application.yaml', 'argocd-application.yml', '.argocd/*.yaml', '.argocd/*.yml', 'applications/*.yaml', 'applications/*.yml'],
    lockFiles: [],
    capabilities: ['update', 'dependency-tree', 'audit', 'tasks', 'toolchain'],
    scopes: ['project', 'repository'],
    scenarios: ['GitOps application sources', 'cluster deployment promotion', 'chart revision governance', 'application drift review'],
    productionTools: ['argocd app diff', 'argocd app get', 'revision pin review'],
    route: '/cloud',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: false,
    healthSupported: true
  },
  {
    id: 'flux',
    name: 'Flux GitOps',
    shortName: 'Flux',
    language: 'GitOps manifests',
    ecosystem: 'Cloud Native',
    packageManager: 'flux',
    category: 'cloud',
    tools: ['flux'],
    manifestFiles: ['flux-kustomization.yaml', 'flux-kustomization.yml', 'flux-helmrelease.yaml', 'flux-helmrelease.yml', 'flux-system/*.yaml', 'flux-system/*.yml'],
    lockFiles: [],
    capabilities: ['update', 'dependency-tree', 'audit', 'tasks', 'toolchain'],
    scopes: ['project', 'repository'],
    scenarios: ['Flux GitRepository and OCIRepository sources', 'HelmRelease chart pins', 'Kustomization path governance', 'cluster drift review'],
    productionTools: ['flux check', 'flux diff', 'flux get all', 'source revision review'],
    route: '/cloud',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: false,
    healthSupported: true
  },
  {
    id: 'terraform',
    name: 'Terraform',
    shortName: 'Terraform',
    language: 'HCL / Infrastructure as Code',
    ecosystem: 'Terraform',
    packageManager: 'Terraform',
    category: 'infrastructure',
    tools: ['terraform'],
    manifestFiles: ['*.tf', '*.tf.json'],
    lockFiles: ['.terraform.lock.hcl'],
    configFiles: ['.terraformrc', 'terraform.rc'],
    capabilities: ['install', 'update', 'dependency-tree', 'audit', 'tasks', 'toolchain', 'registry-config', 'lockfile'],
    scopes: ['project', 'repository'],
    scenarios: ['cloud infrastructure', 'platform modules', 'provider governance', 'deployment pipelines'],
    productionTools: ['terraform init', 'provider lock review', 'validate/plan scanners'],
    route: '/infra',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: false,
    healthSupported: true

  },
  {
    id: 'opentofu',
    name: 'OpenTofu',
    shortName: 'OpenTofu',
    language: 'HCL / Infrastructure as Code',
    ecosystem: 'OpenTofu',
    packageManager: 'OpenTofu',
    category: 'infrastructure',
    tools: ['tofu'],
    manifestFiles: ['*.tf', '*.tf.json'],
    lockFiles: ['.terraform.lock.hcl'],
    configFiles: ['.terraformrc', 'terraform.rc'],
    capabilities: ['install', 'update', 'dependency-tree', 'audit', 'tasks', 'toolchain', 'registry-config', 'lockfile'],
    scopes: ['project', 'repository'],
    scenarios: ['open infrastructure as code', 'provider governance', 'module review', 'deployment pipelines'],
    productionTools: ['tofu init', 'provider lock review', 'validate/plan scanners'],
    route: '/infra',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: false,
    healthSupported: true

  },
  {
    id: 'ansible',
    name: 'Ansible Galaxy',
    shortName: 'Ansible',
    language: 'YAML / Automation',
    ecosystem: 'Ansible',
    packageManager: 'ansible-galaxy',
    category: 'infrastructure',
    tools: ['ansible-galaxy'],
    manifestFiles: ['requirements.yml', 'requirements.yaml', 'collections/requirements.yml', 'roles/requirements.yml'],
    lockFiles: [],
    configFiles: ['ansible.cfg'],
    capabilities: ['install', 'update', 'dependency-tree', 'audit', 'tasks', 'toolchain', 'registry-config'],
    scopes: ['project', 'repository', 'global'],
    scenarios: ['configuration management', 'ops automation', 'playbook collections', 'role governance'],
    productionTools: ['ansible-galaxy collection install', 'ansible-lint', 'requirements review'],
    route: '/infra',
    builtIn: false,
    implemented: false,
    status: 'preview',
    searchable: false,
    healthSupported: true
  },
  {
    id: 'github-actions',
    name: 'GitHub Actions',
    shortName: 'GitHub Actions',
    language: 'YAML / CI',
    ecosystem: 'Automation',
    packageManager: 'GitHub Actions',
    category: 'automation',
    tools: ['gh'],
    manifestFiles: ['.github/workflows/*.yml', '.github/workflows/*.yaml'],
    lockFiles: [],
    detectionFiles: ['.github/workflows'],
    capabilities: ['update', 'audit', 'tasks', 'toolchain', 'lockfile'],
    scopes: ['repository'],
    scenarios: ['CI workflows', 'release automation', 'third-party action governance'],
    productionTools: ['pinned action review', 'workflow policy checks', 'OIDC/token permissions audit'],
    route: '/automation',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  },
  {
    id: 'gitlab-ci',
    name: 'GitLab CI',
    shortName: 'GitLab CI',
    language: 'YAML / CI',
    ecosystem: 'Automation',
    packageManager: 'GitLab CI',
    category: 'automation',
    tools: ['glab'],
    manifestFiles: ['.gitlab-ci.yml', '.gitlab-ci.yaml'],
    lockFiles: [],
    capabilities: ['update', 'audit', 'tasks', 'toolchain'],
    scopes: ['repository'],
    scenarios: ['GitLab pipelines', 'shared CI templates', 'release automation'],
    productionTools: ['include review', 'pipeline lint', 'template pinning'],
    route: '/automation',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  },
  {
    id: 'pre-commit',
    name: 'pre-commit',
    shortName: 'pre-commit',
    language: 'YAML / Developer Tooling',
    ecosystem: 'Automation',
    packageManager: 'pre-commit',
    category: 'automation',
    tools: ['pre-commit'],
    manifestFiles: ['.pre-commit-config.yaml', '.pre-commit-config.yml'],
    lockFiles: [],
    capabilities: ['install', 'update', 'audit', 'tasks', 'toolchain'],
    scopes: ['project', 'repository'],
    scenarios: ['repository hooks', 'format/lint gates', 'developer workstation policy'],
    productionTools: ['pre-commit autoupdate', 'hook pin review', 'CI hook verification'],
    route: '/automation',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  },
  {
    id: 'bazel',
    name: 'Bazel / bzlmod',
    shortName: 'Bazel',
    language: 'Polyglot',
    ecosystem: 'Build Systems',
    packageManager: 'Bazel',
    category: 'build',
    tools: ['bazel'],
    manifestFiles: ['MODULE.bazel', 'WORKSPACE', 'WORKSPACE.bazel', 'BUILD', 'BUILD.bazel'],
    lockFiles: ['MODULE.bazel.lock'],
    configFiles: ['.bazelrc'],
    detectionFiles: ['MODULE.bazel', 'WORKSPACE', 'WORKSPACE.bazel', '.bazelrc'],
    capabilities: ['install', 'update', 'dependency-tree', 'audit', 'tasks', 'toolchain', 'build', 'lockfile', 'sbom'],
    scopes: ['project', 'repository'],
    scenarios: ['polyglot monorepos', 'hermetic builds', 'remote execution', 'ruleset governance'],
    productionTools: ['bazel mod graph', 'bazel mod tidy', 'external repository review'],
    route: '/build',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  },
  {
    id: 'pants',
    name: 'Pants',
    shortName: 'Pants',
    language: 'Python / JVM / Go / Shell',
    ecosystem: 'Build Systems',
    packageManager: 'Pants',
    category: 'build',
    tools: ['pants'],
    manifestFiles: ['pants.toml', 'BUILD', 'BUILD.pants'],
    lockFiles: ['python-default.lock', 'pants.lock', '3rdparty/python/*.lock'],
    configFiles: ['pants.rc', '.pants.rc'],
    detectionFiles: ['pants.toml'],
    capabilities: ['install', 'update', 'dependency-tree', 'audit', 'tasks', 'toolchain', 'build', 'lockfile'],
    scopes: ['project', 'repository'],
    scenarios: ['monorepo dependency inference', 'Python resolves', 'JVM lockfiles', 'CI build graph governance'],
    productionTools: ['pants dependencies', 'pants generate-lockfiles', 'backend package review'],
    route: '/build',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  },
  {
    id: 'buck',
    name: 'Buck / Buck2',
    shortName: 'Buck',
    language: 'Polyglot',
    ecosystem: 'Build Systems',
    packageManager: 'Buck2',
    category: 'build',
    tools: ['buck2'],
    manifestFiles: ['BUCK', 'BUCK.v2', '.buckconfig'],
    lockFiles: [],
    configFiles: ['.buckconfig', '.buckroot'],
    detectionFiles: ['.buckconfig', '.buckroot', 'BUCK.v2'],
    capabilities: ['dependency-tree', 'audit', 'tasks', 'toolchain', 'build', 'sbom'],
    scopes: ['project', 'repository'],
    scenarios: ['large polyglot builds', 'cell dependencies', 'prebuilt artifacts', 'remote execution'],
    productionTools: ['buck2 query', 'buck2 audit dependencies', 'external archive review'],
    route: '/build',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  },
  {
    id: 'opam',
    name: 'opam / OCaml',
    shortName: 'opam',
    language: 'OCaml',
    ecosystem: 'OCaml',
    packageManager: 'opam',
    category: 'systems',
    tools: ['opam'],
    manifestFiles: ['*.opam', 'dune-project'],
    lockFiles: ['opam.locked'],
    configFiles: ['opam-switch'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'dependency-tree', 'audit', 'tasks', 'toolchain', 'lockfile'],
    scopes: ['project', 'environment'],
    scenarios: ['OCaml libraries', 'Dune workspaces', 'compiler switch governance', 'native services'],
    productionTools: ['opam lock', 'opam list --outdated', 'dune build dependency review'],
    route: '/systems',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: true,
    healthSupported: false
  },
  {
    id: 'cpan',
    name: 'CPAN / cpanfile',
    shortName: 'CPAN',
    language: 'Perl',
    ecosystem: 'Perl',
    packageManager: 'cpanm / cpanfile',
    category: 'scripting',
    tools: ['cpanm'],
    manifestFiles: ['cpanfile'],
    lockFiles: ['cpanfile.snapshot'],
    capabilities: ['search', 'install', 'update', 'dependency-tree', 'audit', 'toolchain', 'lockfile'],
    scopes: ['project', 'environment'],
    scenarios: ['Perl services', 'legacy automation', 'CPAN module governance', 'Carton deployments'],
    productionTools: ['cpanfile.snapshot review', 'cpanm --installdeps', 'CPAN audit evidence import'],
    route: '/systems',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: true,
    healthSupported: false
  },
  {
    id: 'luarocks',
    name: 'LuaRocks',
    shortName: 'LuaRocks',
    language: 'Lua',
    ecosystem: 'Lua',
    packageManager: 'LuaRocks',
    category: 'scripting',
    tools: ['luarocks'],
    manifestFiles: ['*.rockspec'],
    lockFiles: ['luarocks.lock'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'dependency-tree', 'audit', 'tasks', 'toolchain', 'lockfile'],
    scopes: ['project', 'environment', 'global'],
    scenarios: ['Lua applications', 'OpenResty services', 'game scripting', 'embedded tooling'],
    productionTools: ['rockspec review', 'luarocks lint', 'lockfile and tree pinning'],
    route: '/systems',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: true,
    healthSupported: false
  },
  {
    id: 'shards',
    name: 'Crystal Shards',
    shortName: 'Shards',
    language: 'Crystal',
    ecosystem: 'Crystal',
    packageManager: 'Shards',
    category: 'systems',
    tools: ['shards'],
    manifestFiles: ['shard.yml'],
    lockFiles: ['shard.lock'],
    capabilities: ['install', 'uninstall', 'update', 'dependency-tree', 'audit', 'tasks', 'toolchain', 'lockfile'],
    scopes: ['project'],
    scenarios: ['Crystal services', 'CLI tools', 'compiled web apps', 'lockfile review'],
    productionTools: ['shards install', 'shards update', 'shard.lock review'],
    route: '/systems',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  },
  {
    id: 'zig',
    name: 'Zig Package Manager',
    shortName: 'Zig',
    language: 'Zig',
    ecosystem: 'Zig',
    packageManager: 'Zig build system',
    category: 'systems',
    tools: ['zig'],
    manifestFiles: ['build.zig.zon', 'build.zig'],
    lockFiles: ['build.zig.zon'],
    configFiles: ['build.zig'],
    capabilities: ['install', 'update', 'dependency-tree', 'tasks', 'toolchain', 'build', 'lockfile'],
    scopes: ['project'],
    scenarios: ['Zig libraries', 'native services', 'cross-compiled CLIs', 'toolchain-pinned builds'],
    productionTools: ['build.zig.zon hash review', 'zig build dependency fetch', 'cross-target build evidence'],
    route: '/systems',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  },
  {
    id: 'homebrew',
    name: 'Homebrew Bundle',
    shortName: 'Homebrew',
    language: 'System Packages',
    ecosystem: 'macOS / Linux developer tools',
    packageManager: 'brew',
    category: 'runtime',
    tools: ['brew'],
    manifestFiles: ['Brewfile'],
    lockFiles: ['Brewfile.lock.json'],
    configFiles: ['.brewrc'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'dependency-tree', 'audit', 'toolchain', 'cache', 'lockfile'],
    scopes: ['environment', 'global', 'repository'],
    scenarios: ['developer workstation bootstrap', 'CI runner prerequisites', 'macOS toolchain governance', 'Linuxbrew environments'],
    productionTools: ['brew bundle check', 'brew bundle lock', 'brew outdated', 'brew doctor'],
    route: '/runtime',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: true,
    healthSupported: false
  },
  {
    id: 'chocolatey',
    name: 'Chocolatey',
    shortName: 'Chocolatey',
    language: 'System Packages',
    ecosystem: 'Windows developer tools',
    packageManager: 'choco',
    category: 'runtime',
    tools: ['choco'],
    manifestFiles: ['packages.config', 'chocolatey.config'],
    lockFiles: [],
    configFiles: ['chocolatey.config'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'dependency-tree', 'audit', 'toolchain', 'cache'],
    scopes: ['environment', 'global', 'repository'],
    scenarios: ['Windows workstation bootstrap', 'build agent prerequisites', 'enterprise package approval', 'tool version governance'],
    productionTools: ['choco outdated', 'packages.config review', 'internal Chocolatey feed checks'],
    route: '/runtime',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: true,
    healthSupported: false
  },
  {
    id: 'scoop',
    name: 'Scoop',
    shortName: 'Scoop',
    language: 'System Packages',
    ecosystem: 'Windows developer tools',
    packageManager: 'scoop',
    category: 'runtime',
    tools: ['scoop'],
    manifestFiles: ['scoopfile.json', 'scoopfile'],
    lockFiles: [],
    configFiles: ['.scooprc'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'dependency-tree', 'audit', 'toolchain', 'cache'],
    scopes: ['environment', 'global', 'repository'],
    scenarios: ['portable Windows toolchains', 'developer laptop bootstrap', 'bucket review', 'CLI version governance'],
    productionTools: ['scoop status', 'scoop export review', 'bucket source pinning'],
    route: '/runtime',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: true,
    healthSupported: false
  },
  {
    id: 'winget',
    name: 'Windows Package Manager',
    shortName: 'winget',
    language: 'System Packages',
    ecosystem: 'Windows developer tools',
    packageManager: 'winget',
    category: 'runtime',
    tools: ['winget'],
    manifestFiles: ['winget-export.json', 'winget-packages.json'],
    lockFiles: [],
    configFiles: ['winget-settings.json'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'dependency-tree', 'audit', 'toolchain'],
    scopes: ['environment', 'global', 'repository'],
    scenarios: ['Windows package baselines', 'golden image drift review', 'enterprise package allowlists', 'build agent bootstrap'],
    productionTools: ['winget export', 'winget upgrade', 'winget source list'],
    route: '/runtime',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: true,
    healthSupported: false
  },
  {
    id: 'asdf',
    name: 'asdf Runtime Manager',
    shortName: 'asdf',
    language: 'Polyglot runtimes',
    ecosystem: 'Runtime version managers',
    packageManager: 'asdf',
    category: 'runtime',
    tools: ['asdf'],
    manifestFiles: ['.tool-versions'],
    lockFiles: [],
    configFiles: ['.asdfrc'],
    capabilities: ['install', 'uninstall', 'update', 'version-switch', 'dependency-tree', 'toolchain', 'lockfile'],
    scopes: ['project', 'environment', 'repository'],
    scenarios: ['polyglot runtime pinning', 'CI runtime parity', 'developer onboarding', 'multi-language repository governance'],
    productionTools: ['asdf install', 'asdf current', '.tool-versions review'],
    route: '/runtime',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  },
  {
    id: 'mise',
    name: 'mise Runtime Manager',
    shortName: 'mise',
    language: 'Polyglot runtimes',
    ecosystem: 'Runtime version managers',
    packageManager: 'mise',
    category: 'runtime',
    tools: ['mise'],
    manifestFiles: ['mise.toml', '.mise.toml'],
    lockFiles: ['mise.lock'],
    configFiles: ['mise.toml', '.mise.toml'],
    capabilities: ['install', 'uninstall', 'update', 'version-switch', 'dependency-tree', 'tasks', 'toolchain', 'lockfile'],
    scopes: ['project', 'environment', 'repository'],
    scenarios: ['polyglot runtime pinning', 'task runner governance', 'CI runtime parity', 'developer onboarding'],
    productionTools: ['mise install', 'mise outdated', 'mise tasks', 'mise lockfile review'],
    route: '/runtime',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  },
  {
    id: 'sdkman',
    name: 'SDKMAN!',
    shortName: 'SDKMAN!',
    language: 'JVM runtimes',
    ecosystem: 'Runtime version managers',
    packageManager: 'sdk',
    category: 'runtime',
    tools: ['sdk'],
    manifestFiles: ['.sdkmanrc'],
    lockFiles: [],
    configFiles: ['.sdkmanrc'],
    capabilities: ['install', 'uninstall', 'update', 'version-switch', 'dependency-tree', 'toolchain', 'lockfile'],
    scopes: ['project', 'environment'],
    scenarios: ['JDK and JVM toolchain pinning', 'Gradle/Maven runtime parity', 'developer shell bootstrap', 'CI image evidence'],
    productionTools: ['sdk env install', 'sdk current', '.sdkmanrc review'],
    route: '/runtime',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  },
  {
    id: 'apt',
    name: 'APT / Debian Packages',
    shortName: 'APT',
    language: 'Linux system packages',
    ecosystem: 'Debian / Ubuntu',
    packageManager: 'apt-get',
    category: 'runtime',
    tools: ['apt-get'],
    manifestFiles: ['apt-packages.txt', 'packages.apt', 'debian-packages.txt'],
    lockFiles: [],
    configFiles: ['apt-sources.list', 'sources.list'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'audit', 'toolchain', 'cache'],
    scopes: ['environment', 'global', 'repository'],
    scenarios: ['Debian and Ubuntu base images', 'CI runner prerequisites', 'Linux workstation bootstrap', 'golden image package baselines'],
    productionTools: ['apt-get update', 'apt-get install', 'apt list --installed', 'apt-mark showmanual'],
    route: '/runtime',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: true,
    healthSupported: false
  },
  {
    id: 'dnf',
    name: 'DNF / RPM Packages',
    shortName: 'DNF',
    language: 'Linux system packages',
    ecosystem: 'Fedora / RHEL / RPM',
    packageManager: 'dnf',
    category: 'runtime',
    tools: ['dnf'],
    manifestFiles: ['dnf-packages.txt', 'rpm-packages.txt', 'packages.dnf'],
    lockFiles: [],
    configFiles: ['dnf.conf', 'yum.conf'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'audit', 'toolchain', 'cache'],
    scopes: ['environment', 'global', 'repository'],
    scenarios: ['Fedora/RHEL build images', 'enterprise Linux package baselines', 'CI runner prerequisites', 'RPM fleet drift review'],
    productionTools: ['dnf check-update', 'dnf upgrade', 'dnf repoquery --installed', 'dnf updateinfo'],
    route: '/runtime',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: true,
    healthSupported: false
  },
  {
    id: 'apk',
    name: 'Alpine apk',
    shortName: 'apk',
    language: 'Linux system packages',
    ecosystem: 'Alpine Linux',
    packageManager: 'apk',
    category: 'runtime',
    tools: ['apk'],
    manifestFiles: ['apk-packages.txt', 'packages.apk'],
    lockFiles: [],
    configFiles: ['repositories.apk', 'apk-repositories.txt'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'audit', 'toolchain', 'cache'],
    scopes: ['environment', 'global', 'repository'],
    scenarios: ['Alpine container images', 'minimal CI runners', 'musl-based runtime images', 'edge package baselines'],
    productionTools: ['apk add', 'apk info', 'apk version', 'apk audit'],
    route: '/runtime',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: true,
    healthSupported: false
  },
  {
    id: 'pacman',
    name: 'pacman / Arch Packages',
    shortName: 'pacman',
    language: 'Linux system packages',
    ecosystem: 'Arch Linux',
    packageManager: 'pacman',
    category: 'runtime',
    tools: ['pacman'],
    manifestFiles: ['pacman-packages.txt', 'packages.pacman'],
    lockFiles: [],
    configFiles: ['pacman.conf'],
    capabilities: ['search', 'install', 'uninstall', 'update', 'audit', 'toolchain', 'cache'],
    scopes: ['environment', 'global', 'repository'],
    scenarios: ['Arch-based developer workstations', 'rolling Linux build images', 'package baseline review', 'system package drift checks'],
    productionTools: ['pacman -Syu', 'pacman -Q', 'pacman -Qu', 'pacman -Qm'],
    route: '/runtime',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: true,
    healthSupported: false
  },
  {
    id: 'nix',
    name: 'Nix Flakes / Shells',
    shortName: 'Nix',
    language: 'Reproducible system environments',
    ecosystem: 'Nix',
    packageManager: 'nix',
    category: 'runtime',
    tools: ['nix'],
    manifestFiles: ['flake.nix', 'shell.nix', 'default.nix'],
    lockFiles: ['flake.lock'],
    configFiles: ['nix.conf', '.envrc'],
    capabilities: ['install', 'update', 'dependency-tree', 'audit', 'tasks', 'toolchain', 'lockfile', 'sbom'],
    scopes: ['project', 'environment', 'repository'],
    scenarios: ['reproducible dev shells', 'hermetic CI environments', 'NixOS package baselines', 'multi-language toolchain pins'],
    productionTools: ['nix develop', 'nix flake show', 'nix flake update', 'nix build'],
    route: '/runtime',
    builtIn: false,
    implemented: false,
    status: 'planned',
    searchable: false,
    healthSupported: false
  }
]

export const IMPLEMENTED_MANAGER_IDS = MANAGER_DEFINITIONS
  .filter((manager): manager is DependencyManagerDefinition & { id: ImplementedPackageManagerId } => manager.implemented)
  .map((manager) => manager.id)

export function getManagerDefinition(id: DependencyManagerId): DependencyManagerDefinition | undefined {
  return MANAGER_DEFINITIONS.find((manager) => manager.id === id)
}

export function getImplementedManagerDefinitions(): Array<DependencyManagerDefinition & { id: ImplementedPackageManagerId }> {
  return MANAGER_DEFINITIONS.filter((manager): manager is DependencyManagerDefinition & { id: ImplementedPackageManagerId } => manager.implemented)
}

export function getPlannedManagerDefinitions(): DependencyManagerDefinition[] {
  return MANAGER_DEFINITIONS.filter((manager) => manager.status === 'planned')
}

export function getPreviewManagerDefinitions(): DependencyManagerDefinition[] {
  return MANAGER_DEFINITIONS.filter((manager) => manager.status === 'preview')
}

export function getManagerRoute(id: DependencyManagerId): string {
  return getManagerDefinition(id)?.route || '/plugins'
}

export function getManagerDetectionFiles(manager: DependencyManagerDefinition): readonly string[] {
  return manager.detectionFiles?.length ? manager.detectionFiles : manager.manifestFiles
}

export function formatManagerFiles(files: readonly string[]): string {
  return files.length > 0 ? files.join(', ') : 'managed by tool metadata'
}
